#!/bin/sh

# bkgs
gbasf2 ./python/gbasf2_Saki.py --force -p UUBAR_CTRL_1 -i /belle/collection/MC/MC15ri_uubar_1abinv_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type uubar --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p DDBAR_CTRL_1 -i /belle/collection/MC/MC15ri_ddbar_1abinv_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type ddbar --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p SSBAR_CTRL_1 -i /belle/collection/MC/MC15ri_ssbar_1abinv_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type ssbar --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p CCBAR_CTRL_1 -i /belle/collection/MC/MC15ri_ccbar_1abinv_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type ccbar --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p MUMU_CTRL_1 -i /belle/collection/MC/MC15ri_mumu_1abinv_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type mumu --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p TAUTAU_CTRL_1 -i /belle/collection/MC/MC15ri_taupair_1abinv_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type taupair --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p MIX_CTRL_1 -i /belle/collection/MC/MC15ri_mixed_1abinv_v2 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type mixed --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p MIX_CTRL_2 -i /belle/collection/MC/MC15ri_mixed_2abinv_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type mixed --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p MIX_CTRL_3 -i /belle/collection/MC/MC15ri_mixed_3abinv_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type mixed --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p CHG_CTRL_1 -i /belle/collection/MC/MC15ri_charged_1abinv_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type charged --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p CHG_CTRL_2 -i /belle/collection/MC/MC15ri_charged_2abinv_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type charged --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p CHG_CTRL_3 -i /belle/collection/MC/MC15ri_charged_3abinv_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type charged --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p EE_CTRL_1 -i /belle/collection/MC/MC15ri_ee_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type ee --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p GG_CTRL_1 -i 	/belle/collection/MC/MC15ri_gg_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type gg --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p EEEE_CTRL_1 -i /belle/collection/MC/MC15ri_eeee_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type eeee --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p EEKK_CTRL_1 -i /belle/collection/MC/MC15ri_eeKK_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type eeKK --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p EETAUTAU_CTRL_1 -i /belle/collection/MC/MC15ri_eetautau_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type eetautau --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p EEMUMU_CTRL_1 -i /belle/collection/MC/MC15ri_eemumu_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type eemumu --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p EEPIPI_CTRL_1 -i /belle/collection/MC/MC15ri_eepipi_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type eepipi --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p EEPP_CTRL_1 -i /belle/collection/MC/MC15ri_eepp_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type eepp --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p K0K0ISR_CTRL_1 -i /belle/collection/MC/MC15ri_K0K0barISR_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type K0K0barISR --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p KKISR_CTRL_1 -i /belle/collection/MC/MC15ri_KKISR_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type KKISR --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p MUMUMUMU_CTRL_1 -i /belle/collection/MC/MC15ri_mumumumu_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type mumumumu --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p MUMUTAUTAU_CTRL_1 -i /belle/collection/MC/MC15ri_mumutautau_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type mumutautau --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p PIPIISR_CTRL_1 -i 	/belle/collection/MC/MC15ri_pipiISR_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type pipiISR --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p PIPIPI0ISR_CTRL_1 -i /belle/collection/MC/MC15ri_pipipi0ISR_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type pipipi0ISR --energy 4S --control"
gbasf2 ./python/gbasf2_Saki.py --force -p TAUTAUTAUTAU_CTRL_1 -i /belle/collection/MC/MC15ri_tautautautau_v1 -s light-2505-deimos --cputime 1600 --basf2opt="-- --sample MC15ri --type tautautautau --energy 4S --control"
